In [45]:
import pandas as pd
import numpy as np

df = pd.read_csv("data.csv")

df.head()
df.info()          
df.describe(include="all")
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 113097 entries, 0 to 113096
Data columns (total 18 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   warehouse_inventory_level        113097 non-null  float64
 1   handling_equipment_availability  113097 non-null  float64
 2   order_fulfillment_status         113097 non-null  float64
 3   weather_condition_severity       113097 non-null  float64
 4   shipping_costs                   113097 non-null  float64
 5   supplier_reliability_score       113097 non-null  float64
 6   lead_time_days                   113097 non-null  float64
 7   historical_demand                113097 non-null  float64
 8   cargo_condition_status           113097 non-null  float64
 9   route_risk_level                 113097 non-null  float64
 10  customs_clearance_time           113097 non-null  float64
 11  disruption_likelihood_score      113097 non-null  float64
 12  delay_probability                113097 non-null  float64
 13  risk_classification              113097 non-null  str
 14  delivery_time_deviation          113097 non-null  float64
 15  product_id                       113097 non-null  str
 16  supplier_id                      113097 non-null  str
 17  supplier_country                 113097 non-null  str
dtypes: float64(14), str(4)
memory usage: 18.8 MB

(113097, 18)

In [46]:
df.columns = (df.columns.str.strip()
                         .str.lower()
                         .str.replace(r"\s+", "_", regex=True))

In [47]:
df.isna().sum().sort_values(ascending=False)

warehouse_inventory_level          0
handling_equipment_availability    0
supplier_id                        0
product_id                         0
delivery_time_deviation            0
risk_classification                0
delay_probability                  0
disruption_likelihood_score        0
customs_clearance_time             0
route_risk_level                   0
cargo_condition_status             0
historical_demand                  0
lead_time_days                     0
supplier_reliability_score         0
shipping_costs                     0
weather_condition_severity         0
order_fulfillment_status           0
supplier_country                   0
dtype: int64

In [6]:
df.duplicated().sum()
df = df.drop_duplicates()

In [7]:
display(df.describe().T)
non_negative_cols = [
    "warehouse_inventory_level",
    "shipping_costs",
    "historical_demand"
]

,count,mean,std,min,25%,50%,75%,max
warehouse_inventory_level,113097.0,300.378420,323.860477,1.320000e-12,16.296174,159.126186,542.583327,999.999299
handling_equipment_availability,113097.0,0.303599,0.326512,4.570000e-16,0.017291,0.159642,0.556574,0.999999
order_fulfillment_status,113097.0,0.600992,0.345996,1.320000e-06,0.276788,0.681859,0.938873,1.000000
weather_condition_severity,113097.0,0.497895,0.353455,4.540000e-09,0.144156,0.497966,0.850755,1.000000
shipping_costs,113097.0,459.696347,312.319187,1.000000e+02,153.869113,389.202356,754.167627,999.999853
supplier_reliability_score,113097.0,0.500708,0.353932,6.900000e-10,0.144437,0.502877,0.854850,1.000000
lead_time_days,113097.0,5.216388,4.517152,1.000000e+00,1.237201,3.282951,8.611542,14.999995
historical_demand,113097.0,6019.928559,3429.394766,1.000030e+02,2821.510422,6786.803625,9372.022086,10000.000000
cargo_condition_status,113097.0,0.297268,0.321501,7.260000e-19,0.016840,0.155386,0.540047,1.000000
route_risk_level,113097.0,6.996506,3.236633,4.970000e-05,4.581787,8.376387,9.835310,10.000000
customs_clearance_time,113097.0,2.296624,1.555277,5.000000e-01,0.777328,1.942439,3.749471,5.000000
disruption_likelihood_score,113097.0,0.803447,0.279062,4.770000e-05,0.691751,0.958108,0.998764,1.000000
delay_probability,113097.0,0.699617,0.324297,3.130000e-06,0.456054,0.840807,0.982401,1.000000
delivery_time_deviation,113097.0,5.170553,4.158751,-1.999998e+00,1.259607,6.088516,9.247708,10.000000

In [9]:
columns_to_check = [
    "supplier_id",
    "supplier_country",
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]
for col in columns_to_check:
    if col in df.columns:
        print(f"\n--- {col} ---")
        print("Unique values:", df[col].nunique())
        print(df[col].value_counts(dropna=False).head(20))

if "supplier_id" in df.columns:
    supplier_counts = df.groupby("supplier_id").size()

    print("\nNumber of suppliers:", supplier_counts.size)
    print("\nRecords per supplier:")
    print(supplier_counts.describe())

--- supplier_id ---
Unique values: 3524
supplier_id
P0517_S1    56
P0517_S2    56
P0652_S1    50
P0652_S2    50
P0652_S3    50
P0977_S1    49
P0977_S2    49
P0459_S1    48
P0459_S2    48
P0459_S3    48
P0459_S4    48
P0459_S5    48
P0437_S1    46
P0437_S2    46
P0437_S3    46
P0475_S1    46
P0475_S2    46
P0475_S3    46
P0969_S1    46
P0969_S2    46
Name: count, dtype: int64

--- supplier_country ---
Unique values: 94
supplier_country
Vietnam                   1896
Dominican Republic        1822
Trinidad and Tobago       1737
UK                        1550
Philippines               1544
Australia                 1528
Kyrgyzstan                1523
Bulgaria                  1508
Georgia                   1497
Myanmar                   1495
Jordan                    1489
Colombia                  1487
Romania                   1482
Ethiopia                  1472
Germany                   1469
Bosnia and Herzegovina    1460
Morocco                   1421
Bangladesh                1416
Portugal                  1413
North Macedonia           1387
Name: count, dtype: int64

--- order_fulfillment_status ---
Unique values: 32044
order_fulfillment_status
1.000000    9
0.991061    9
1.000000    9
1.000000    8
0.999938    8
1.000000    8
0.999976    8
1.000000    7
1.000000    7
0.995404    7
1.000000    7
0.943737    7
0.999999    7
1.000000    6
1.000000    6
0.152742    5
0.811885    5
0.153994    5
0.779766    5
0.999889    5
Name: count, dtype: int64

--- cargo_condition_status ---
Unique values: 31572
cargo_condition_status
1.230000e-05    23
5.520000e-05    22
1.450000e-06    20
3.360000e-05    20
1.340000e-05    19
3.460000e-05    18
7.520000e-05    18
1.150000e-05    17
1.030000e-05    17
1.570000e-05    16
1.050000e-05    16
2.780000e-05    16
4.150000e-06    15
5.050000e-05    15
1.790000e-05    15
3.850000e-05    15
5.200000e-07    15
1.390000e-06    15
1.240000e-05    15
1.660000e-05    15
Name: count, dtype: int64

--- delivery_time_deviation ---
Unique values: 32057
delivery_time_deviation
 10.000000    10
 10.000000     8
 10.000000     7
 10.000000     7
 9.999997      7
 1.283594      5
 9.304897      5
 9.201606      5
 8.111611      5
 9.998838      5
 8.059741      5
 9.999586      5
 8.838364      5
 7.480515      5
 9.427747      5
 4.730362      5
 8.911311      5
 8.884998      5
 7.630722      5
-0.691637      5
Name: count, dtype: int64

Number of suppliers: 3524

Records per supplier:
count    3524.000000
mean       32.093360
std         5.745484
min        16.000000
25%        28.000000
50%        32.000000
75%        36.000000
max        56.000000
dtype: float64

In [10]:

candidate_cols = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation",
    "supplier_id"
]

display(df[candidate_cols].describe(include="all").T)

for col in ["order_fulfillment_status", "cargo_condition_status"]:
    if col in df.columns:
        print(f"\n{col}")
        print("Minimum:", df[col].min())
        print("Maximum:", df[col].max())
        print("Values between 0 and 1:",
              df[col].between(0, 1).mean() * 100, "%")

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_fulfillment_status,113097.0,NaN,NaN,NaN,0.600992,0.345996,0.000001,0.276788,0.681859,0.938873,1.0
cargo_condition_status,113097.0,NaN,NaN,NaN,0.297268,0.321501,0.0,0.01684,0.155386,0.540047,1.0
delivery_time_deviation,113097.0,NaN,NaN,NaN,5.170553,4.158751,-1.999998,1.259607,6.088516,9.247708,10.0
supplier_id,113097,3524,P0517_S1,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN

order_fulfillment_status
Minimum: 1.32e-06
Maximum: 1.0
Values between 0 and 1: 100.0 %

cargo_condition_status
Minimum: 7.26e-19
Maximum: 0.999999983
Values between 0 and 1: 100.0 %

In [11]:
cols = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]

# 1. Distribution statistics
display(df[cols].describe().T)

# 2. Correlations between candidate indicators
display(df[cols].corr(numeric_only=True))

# 3. Check delivery deviation
print("Delivery deviation minimum:",
      df["delivery_time_deviation"].min())

print("Delivery deviation maximum:",
      df["delivery_time_deviation"].max())

print("Negative deviations:",
      (df["delivery_time_deviation"] < 0).sum())

print("Positive deviations:",
      (df["delivery_time_deviation"] > 0).sum())

# 4. Inspect relationships between indicators
display(
    df[cols]
    .sample(min(10, len(df)), random_state=42)
)

,count,mean,std,min,25%,50%,75%,max
order_fulfillment_status,113097.0,0.600992,0.345996,1.320000e-06,0.276788,0.681859,0.938873,1.0
cargo_condition_status,113097.0,0.297268,0.321501,7.260000e-19,0.016840,0.155386,0.540047,1.0
delivery_time_deviation,113097.0,5.170553,4.158751,-1.999998e+00,1.259607,6.088516,9.247708,10.0

,order_fulfillment_status,cargo_condition_status,delivery_time_deviation
order_fulfillment_status,1.000000,0.010078,0.004435
cargo_condition_status,0.010078,1.000000,-0.000157
delivery_time_deviation,0.004435,-0.000157,1.000000

Delivery deviation minimum: -1.999997989
Delivery deviation maximum: 10.0
Negative deviations: 20302
Positive deviations: 92795

,order_fulfillment_status,cargo_condition_status,delivery_time_deviation
42613,0.088653,0.569809,3.361552
8682,0.008172,0.002946,-1.130287
35729,0.429255,0.000937,3.354847
651,0.006549,0.019097,2.338140
71566,0.265051,0.181977,9.951323
35420,0.954254,0.900629,9.256592
45841,0.491520,0.270401,5.545481
99424,0.989728,0.952670,9.137209
66825,0.801469,0.049785,9.681885
94659,0.895698,0.974721,8.323455

In [12]:
cols = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]

# Full-dataset statistics
display(df[cols].describe().T)

# Correlation matrix
print("Correlation matrix:")
display(df[cols].corr())

# Check whether delivery deviation can define late delivery
print("Delivery deviation counts:")
print("Negative:", (df["delivery_time_deviation"] < 0).sum())
print("Zero:", (df["delivery_time_deviation"] == 0).sum())
print("Positive:", (df["delivery_time_deviation"] > 0).sum())

# Create a provisional late-delivery label for inspection only
df["late_delivery_check"] = (
    df["delivery_time_deviation"] > 0
).astype(int)

print("\nProvisional label distribution:")
print(df["late_delivery_check"].value_counts())
print(df["late_delivery_check"].value_counts(normalize=True))

,count,mean,std,min,25%,50%,75%,max
order_fulfillment_status,113097.0,0.600992,0.345996,1.320000e-06,0.276788,0.681859,0.938873,1.0
cargo_condition_status,113097.0,0.297268,0.321501,7.260000e-19,0.016840,0.155386,0.540047,1.0
delivery_time_deviation,113097.0,5.170553,4.158751,-1.999998e+00,1.259607,6.088516,9.247708,10.0

Correlation matrix:

,order_fulfillment_status,cargo_condition_status,delivery_time_deviation
order_fulfillment_status,1.000000,0.010078,0.004435
cargo_condition_status,0.010078,1.000000,-0.000157
delivery_time_deviation,0.004435,-0.000157,1.000000

Delivery deviation counts:
Negative: 20302
Zero: 0
Positive: 92795

Provisional label distribution:
late_delivery_check
1    92795
0    20302
Name: count, dtype: int64
late_delivery_check
1    0.82049
0    0.17951
Name: proportion, dtype: float64

In [13]:
# Provisional target for analysis only
y = (df["delivery_time_deviation"] > 0).astype(int)

features = [
    "order_fulfillment_status",
    "cargo_condition_status"
]

# Compare the candidate indicators across the two groups
comparison = df.groupby(y.rename("provisional_late"))[features].agg(
    ["mean", "median", "std", "min", "max"]
)

display(comparison)

# Check correlations
analysis_df = df[features].copy()
analysis_df["provisional_late"] = y

print("\nCorrelation with provisional label:")
display(
    analysis_df.corr(numeric_only=True)["provisional_late"]
    .sort_values(ascending=False)
)

# Check whether the indicators have enough variation
print("\nUnique values:")
print(df[features].nunique())

                 order_fulfillment_status                                     \
                                     mean    median       std       min  max
provisional_late
0                                 0.60219  0.685629  0.344259  0.000003  1.0
1                                 0.60073  0.680662  0.346376  0.000001  1.0

                 cargo_condition_status                                    \
                                   mean    median       std           min
provisional_late
0                              0.297116  0.155123  0.320151  7.260000e-19
1                              0.297301  0.155580  0.321798  2.570000e-17


                       max
provisional_late
0                 0.999995
1                 1.000000

Correlation with provisional label:

provisional_late            1.00000
cargo_condition_status      0.00022
order_fulfillment_status   -0.00162
Name: provisional_late, dtype: float64

Unique values:
order_fulfillment_status    32044
cargo_condition_status      31572
dtype: int64

In [14]:
# Inspect numerical columns and their ranges
numeric_cols = df.select_dtypes(include="number").columns

display(df[numeric_cols].describe().T)

# Check whether delivery deviation is related to other numeric variables
corr = df[numeric_cols].corr()

display(
    corr["delivery_time_deviation"]
    .sort_values(ascending=False)
    .to_frame("correlation_with_delivery_deviation")
)

,count,mean,std,min,25%,50%,75%,max
warehouse_inventory_level,113097.0,300.378420,323.860477,1.320000e-12,16.296174,159.126186,542.583327,999.999299
handling_equipment_availability,113097.0,0.303599,0.326512,4.570000e-16,0.017291,0.159642,0.556574,0.999999
order_fulfillment_status,113097.0,0.600992,0.345996,1.320000e-06,0.276788,0.681859,0.938873,1.000000
weather_condition_severity,113097.0,0.497895,0.353455,4.540000e-09,0.144156,0.497966,0.850755,1.000000
shipping_costs,113097.0,459.696347,312.319187,1.000000e+02,153.869113,389.202356,754.167627,999.999853
supplier_reliability_score,113097.0,0.500708,0.353932,6.900000e-10,0.144437,0.502877,0.854850,1.000000
lead_time_days,113097.0,5.216388,4.517152,1.000000e+00,1.237201,3.282951,8.611542,14.999995
historical_demand,113097.0,6019.928559,3429.394766,1.000030e+02,2821.510422,6786.803625,9372.022086,10000.000000
cargo_condition_status,113097.0,0.297268,0.321501,7.260000e-19,0.016840,0.155386,0.540047,1.000000
route_risk_level,113097.0,6.996506,3.236633,4.970000e-05,4.581787,8.376387,9.835310,10.000000
customs_clearance_time,113097.0,2.296624,1.555277,5.000000e-01,0.777328,1.942439,3.749471,5.000000
disruption_likelihood_score,113097.0,0.803447,0.279062,4.770000e-05,0.691751,0.958108,0.998764,1.000000
delay_probability,113097.0,0.699617,0.324297,3.130000e-06,0.456054,0.840807,0.982401,1.000000
delivery_time_deviation,113097.0,5.170553,4.158751,-1.999998e+00,1.259607,6.088516,9.247708,10.000000
late_delivery_check,113097.0,0.820490,0.383780,0.000000e+00,1.000000,1.000000,1.000000,1.000000

                                 correlation_with_delivery_deviation
delivery_time_deviation                                     1.000000
late_delivery_check                                         0.720983
delay_probability                                           0.005037
supplier_reliability_score                                  0.004568
order_fulfillment_status                                    0.004435
shipping_costs                                              0.003769
disruption_likelihood_score                                 0.002253
weather_condition_severity                                  0.001368
cargo_condition_status                                     -0.000157
historical_demand                                          -0.000173
route_risk_level                                           -0.000184
handling_equipment_availability                            -0.001203
lead_time_days                                             -0.002136
warehouse_inventory_level                                  -0.003036
customs_clearance_time                                     -0.008466

In [15]:
# Summarize candidate indicators by supplier
supplier_summary = df.groupby("supplier_id").agg(
    shipment_records=("supplier_id", "size"),
    fulfillment_mean=("order_fulfillment_status", "mean"),
    cargo_condition_mean=("cargo_condition_status", "mean"),
    delivery_deviation_mean=("delivery_time_deviation", "mean"),
    delivery_deviation_std=("delivery_time_deviation", "std")
)

display(supplier_summary.describe().T)

# Inspect 10 suppliers
display(supplier_summary.head(10))

,count,mean,std,min,25%,50%,75%,max
shipment_records,3524.0,32.093360,5.745484,16.000000,28.000000,32.000000,36.000000,56.000000
fulfillment_mean,3524.0,0.601561,0.062063,0.378305,0.559163,0.601062,0.642168,0.786158
cargo_condition_mean,3524.0,0.297835,0.055833,0.110169,0.261049,0.294920,0.333019,0.477958
delivery_deviation_mean,3524.0,5.174668,0.749082,2.687546,4.683928,5.169313,5.681974,7.651201
delivery_deviation_std,3524.0,4.145557,0.320795,3.097604,3.945834,4.166470,4.356654,5.057406

,shipment_records,fulfillment_mean,cargo_condition_mean,delivery_deviation_mean,delivery_deviation_std
supplier_id,,,,,
P0001_S1,25,0.657594,0.219251,5.017376,4.024730
P0001_S2,25,0.657594,0.219251,5.017376,4.024730
P0002_S1,36,0.668762,0.254522,4.683838,4.746545
P0002_S2,36,0.668762,0.254522,4.683838,4.746545
P0002_S3,36,0.668762,0.254522,4.683838,4.746545
P0003_S1,37,0.586810,0.213505,4.419323,4.281972
P0003_S2,37,0.586810,0.213505,4.419323,4.281972
P0003_S3,37,0.586810,0.213505,4.419323,4.281972
P0003_S4,37,0.586810,0.213505,4.419323,4.281972
P0004_S1,26,0.572918,0.317257,5.392035,3.613364

In [17]:

df["product_prefix"] = df["supplier_id"].str.split("_").str[0]

check_cols = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]

supplier_summary = df.groupby("supplier_id")[check_cols].mean()

supplier_summary["product_prefix"] = (
    supplier_summary.index.to_series().str.split("_").str[0].values
)

# Number of distinct aggregate profiles within each product prefix
profile_counts = (
    supplier_summary.groupby("product_prefix")[check_cols]
    .apply(lambda group: len(group.drop_duplicates()))
)

print("Product prefixes:", len(profile_counts))
print("Prefixes with identical supplier profiles:",
      (profile_counts == 1).sum())
print("Prefixes with multiple supplier profiles:",
      (profile_counts > 1).sum())

display(profile_counts.value_counts().sort_index())

Product prefixes: 1000
Prefixes with identical supplier profiles: 1000
Prefixes with multiple supplier profiles: 0

1    1000
Name: count, dtype: int64

In [18]:

# Create a product prefix from supplier_id
df["product_prefix"] = df["supplier_id"].str.split("_").str[0]

# Compare the number of unique values per product prefix
check_cols = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]

for col in check_cols:
    unique_counts = (
        df.groupby("product_prefix")[col]
        .nunique()
    )

    print(f"\n{col}")
    print("Prefixes with only one unique value:",
          (unique_counts == 1).sum())
    print("Total prefixes:", len(unique_counts))

# Compare supplier-level profiles within each product prefix
supplier_profiles = (
    df.groupby(["product_prefix", "supplier_id"])[check_cols]
    .mean()
    .reset_index()
)

profile_counts = (
    supplier_profiles.groupby("product_prefix")[check_cols]
    .apply(lambda x: len(x.drop_duplicates()))
)

print("\nDistinct supplier profiles per product prefix:")
print(profile_counts.value_counts().sort_index())

order_fulfillment_status
Prefixes with only one unique value: 0
Total prefixes: 1000

cargo_condition_status
Prefixes with only one unique value: 0
Total prefixes: 1000

delivery_time_deviation
Prefixes with only one unique value: 0
Total prefixes: 1000

Distinct supplier profiles per product prefix:
1    1000
Name: count, dtype: int64

In [19]:
# Inspect target candidates and supplier/product structure
print("Rows:", len(df))
print("Unique supplier IDs:", df["supplier_id"].nunique())
print("Unique product IDs:", df["product_id"].nunique())

print("\nOrder fulfillment status:")
print(df["order_fulfillment_status"].describe())

print("\nCargo condition status:")
print(df["cargo_condition_status"].describe())

print("\nDelivery time deviation:")
print(df["delivery_time_deviation"].describe())

# Check whether supplier IDs map to multiple product IDs
products_per_supplier = df.groupby("supplier_id")["product_id"].nunique()
print("\nProducts per supplier:")
print(products_per_supplier.describe())

# Check whether product IDs map to multiple supplier IDs
suppliers_per_product = df.groupby("product_id")["supplier_id"].nunique()
print("\nSuppliers per product:")
print(suppliers_per_product.describe())

Rows: 113097
Unique supplier IDs: 3524
Unique product IDs: 1000

Order fulfillment status:
count    113097.000000
mean          0.600992
std           0.345996
min           0.000001
25%           0.276788
50%           0.681859
75%           0.938873
max           1.000000
Name: order_fulfillment_status, dtype: float64

Cargo condition status:
count    1.130970e+05
mean     2.972676e-01
std      3.215012e-01
min      7.260000e-19
25%      1.684023e-02
50%      1.553862e-01
75%      5.400466e-01
max      1.000000e+00
Name: cargo_condition_status, dtype: float64

Delivery time deviation:
count    113097.000000
mean          5.170553
std           4.158751
min          -1.999998
25%           1.259607
50%           6.088516
75%           9.247708
max          10.000000
Name: delivery_time_deviation, dtype: float64

Products per supplier:
count    3524.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: product_id, dtype: float64

Suppliers per product:
count    1000.000000
mean        3.524000
std         1.112952
min         2.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         5.000000
Name: supplier_id, dtype: float64

In [20]:
indicators = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]

for col in indicators:
    supplier_means = df.groupby("supplier_id")[col].mean()

    print(f"\n--- {col} ---")
    print("Overall standard deviation:", df[col].std())
    print("Standard deviation of supplier means:", supplier_means.std())
    print("Unique supplier means:", supplier_means.nunique())

--- order_fulfillment_status ---
Overall standard deviation: 0.34599598492543987
Standard deviation of supplier means: 0.062063206363438
Unique supplier means: 1000

--- cargo_condition_status ---
Overall standard deviation: 0.321501218887057
Standard deviation of supplier means: 0.055832760994139384
Unique supplier means: 1000

--- delivery_time_deviation ---
Overall standard deviation: 4.158751202256843
Standard deviation of supplier means: 0.7490818055273006
Unique supplier means: 1000

In [21]:
df["product_prefix"] = (
    df["supplier_id"].astype(str).str.split("_").str[0]
)

indicators = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]

supplier_means = (
    df.groupby(["product_prefix", "supplier_id"])[indicators]
      .mean()
      .reset_index()
)

print("Unique product prefixes:", df["product_prefix"].nunique())
print("Unique supplier IDs:", df["supplier_id"].nunique())

for col in indicators:
    variation = (
        supplier_means.groupby("product_prefix")[col]
        .nunique()
    )

    print(f"\n{col}")
    print("Product prefixes with different supplier means:",
          (variation > 1).sum())
    print("Total product prefixes:", len(variation))

Unique product prefixes: 1000
Unique supplier IDs: 3524

order_fulfillment_status
Product prefixes with different supplier means: 0
Total product prefixes: 1000

cargo_condition_status
Product prefixes with different supplier means: 0
Total product prefixes: 1000

delivery_time_deviation
Product prefixes with different supplier means: 0
Total product prefixes: 1000

In [22]:
print(df[
    [
        "order_fulfillment_status",
        "cargo_condition_status",
        "delivery_time_deviation"
    ]
].describe())

print("\nSample records:")
print(
    df[
        [
            "product_id",
            "supplier_id",
            "order_fulfillment_status",
            "cargo_condition_status",
            "delivery_time_deviation"
        ]
    ].head(15).to_string(index=False)
)

       order_fulfillment_status  cargo_condition_status  \
count             113097.000000            1.130970e+05
mean                   0.600992            2.972676e-01
std                    0.345996            3.215012e-01
min                    0.000001            7.260000e-19
25%                    0.276788            1.684023e-02
50%                    0.681859            1.553862e-01
75%                    0.938873            5.400466e-01
max                    1.000000            1.000000e+00

       delivery_time_deviation
count            113097.000000
mean                  5.170553
std                   4.158751
min                  -1.999998
25%                   1.259607
50%                   6.088516
75%                   9.247708
max                  10.000000

Sample records:
product_id supplier_id  order_fulfillment_status  cargo_condition_status  delivery_time_deviation
     P0353    P0353_S1                  0.761166                0.777263                 9.110682
     P0353    P0353_S2                  0.761166                0.777263                 9.110682
     P0353    P0353_S3                  0.761166                0.777263                 9.110682
     P0857    P0857_S1                  0.196594                0.091839                 8.175281
     P0857    P0857_S2                  0.196594                0.091839                 8.175281
     P0857    P0857_S3                  0.196594                0.091839                 8.175281
     P0857    P0857_S4                  0.196594                0.091839                 8.175281
     P0300    P0300_S1                  0.152742                0.253529                 1.283594
     P0300    P0300_S2                  0.152742                0.253529                 1.283594
     P0300    P0300_S3                  0.152742                0.253529                 1.283594
     P0300    P0300_S4                  0.152742                0.253529                 1.283594
     P0300    P0300_S5                  0.152742                0.253529                 1.283594
     P0975    P0975_S1                  0.811885                0.877576                 9.304897
     P0975    P0975_S2                  0.811885                0.877576                 9.304897
     P0975    P0975_S3                  0.811885                0.877576                 9.304897

In [23]:

cols = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]

profiles = df.groupby("product_id")[cols].nunique()

print("Total products:", len(profiles))
print("Products with all three indicators identical across rows:",
      (profiles.eq(1).all(axis=1)).sum())
print("Products with at least one indicator varying across rows:",
      (~profiles.eq(1).all(axis=1)).sum())

print("\nProducts with variation:")
print(profiles.loc[~profiles.eq(1).all(axis=1)].head(10))

Total products: 1000
Products with all three indicators identical across rows: 0
Products with at least one indicator varying across rows: 1000

Products with variation:
            order_fulfillment_status  cargo_condition_status  \
product_id
P0001                             25                      25
P0002                             36                      36
P0003                             37                      37
P0004                             26                      26
P0005                             30                      30
P0006                             34                      34
P0007                             34                      34
P0008                             32                      32
P0009                             35                      35
P0010                             31                      31

            delivery_time_deviation
product_id
P0001                            25
P0002                            36
P0003                            37
P0004                            26
P0005                            30
P0006                            34
P0007                            34
P0008                            32
P0009                            35
P0010                            31

In [24]:

cols = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]

print("Unique values per product:")
print(df.groupby("product_id")[cols].nunique().describe())

print("\nUnique values per supplier:")
print(df.groupby("supplier_id")[cols].nunique().describe())

print("\nNumber of suppliers per product:")
print(df.groupby("product_id")["supplier_id"].nunique().describe())

Unique values per product:
       order_fulfillment_status  cargo_condition_status  \
count                1000.00000             1000.000000
mean                   32.06500               32.064000
std                     5.78725                5.785964
min                    16.00000               16.000000
25%                    28.00000               28.000000
50%                    32.00000               32.000000
75%                    36.00000               36.000000
max                    56.00000               56.000000

       delivery_time_deviation
count               1000.00000
mean                  32.06500
std                    5.78725
min                   16.00000
25%                   28.00000
50%                   32.00000
75%                   36.00000
max                   56.00000

Unique values per supplier:
       order_fulfillment_status  cargo_condition_status  \
count               3524.000000             3524.000000
mean                  32.093360               32.092225
std                    5.745484                5.744020
min                   16.000000               16.000000
25%                   28.000000               28.000000
50%                   32.000000               32.000000
75%                   36.000000               36.000000
max                   56.000000               56.000000

       delivery_time_deviation
count              3524.000000
mean                 32.093360
std                   5.745484
min                  16.000000
25%                  28.000000
50%                  32.000000
75%                  36.000000
max                  56.000000

Number of suppliers per product:
count    1000.000000
mean        3.524000
std         1.112952
min         2.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         5.000000
Name: supplier_id, dtype: float64

In [25]:


indicators = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation"
]

supplier_means = (
    df.groupby(["product_id", "supplier_id"])[indicators]
      .mean()
      .reset_index()
)

for col in indicators:
    differences = (
        supplier_means.groupby("product_id")[col]
        .agg(lambda x: x.max() - x.min())
    )

    print(f"\n{col}")
    print("Products with different supplier means:",
          (differences > 1e-10).sum())
    print("Maximum difference between supplier means:",
          differences.max())

order_fulfillment_status
Products with different supplier means: 0
Maximum difference between supplier means: 0.0

cargo_condition_status
Products with different supplier means: 0
Maximum difference between supplier means: 0.0

delivery_time_deviation
Products with different supplier means: 0
Maximum difference between supplier means: 0.0

In [28]:

import pandas as pd
import numpy as np

# Columns relevant to supplier reliability and lead time
columns = [
    "product_id",
    "supplier_id",
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation",
    "customs_clearance_time",
    "lead_time_days",
    "supplier_reliability_score"
]

# Keep only columns that exist in the dataset
available_columns = [col for col in columns if col in df.columns]

print("Dataset shape:", df.shape)
print("\nAvailable columns:", available_columns)

# 1. Check how many records each supplier has
supplier_records = (
    df.groupby("supplier_id")
      .agg(
          record_count=("supplier_id", "size"),
          unique_products=("product_id", "nunique")
      )
)

print("\nSupplier record-count summary:")
print(supplier_records["record_count"].describe())

print("\nSuppliers associated with multiple products:")
print((supplier_records["unique_products"] > 1).sum())

# 2. Examine performance indicators
performance_columns = [
    "order_fulfillment_status",
    "cargo_condition_status",
    "delivery_time_deviation",
    "customs_clearance_time"
]

print("\nPerformance indicator statistics:")
print(df[performance_columns].describe().T)

# 3. Compare suppliers within the same product
supplier_product_means = (
    df.groupby(["product_id", "supplier_id"])[performance_columns]
      .mean()
      .reset_index()
)

print("\nSupplier-level averages for the same product:")
print(supplier_product_means.head(15).to_string(index=False))

# 4. Check whether suppliers within a product have different average values
variation = (
    supplier_product_means
    .groupby("product_id")[performance_columns]
    .nunique()
)

print("\nProducts where supplier averages differ:")
print((variation > 1).sum())

# 5. Check for missing values and invalid numeric entries
print("\nMissing values:")
print(df[performance_columns].isna().sum())

Dataset shape: (113097, 18)

Available columns: ['product_id', 'supplier_id', 'order_fulfillment_status', 'cargo_condition_status', 'delivery_time_deviation', 'customs_clearance_time', 'lead_time_days', 'supplier_reliability_score']

Supplier record-count summary:
count    3524.000000
mean       32.093360
std         5.745484
min        16.000000
25%        28.000000
50%        32.000000
75%        36.000000
max        56.000000
Name: record_count, dtype: float64

Suppliers associated with multiple products:
0

Performance indicator statistics:
                             count      mean       std           min  \
order_fulfillment_status  113097.0  0.600992  0.345996  1.320000e-06
cargo_condition_status    113097.0  0.297268  0.321501  7.260000e-19
delivery_time_deviation   113097.0  5.170553  4.158751 -1.999998e+00
customs_clearance_time    113097.0  2.296624  1.555277  5.000000e-01

                               25%       50%       75%   max
order_fulfillment_status  0.276788  0.681859  0.938873   1.0
cargo_condition_status    0.016840  0.155386  0.540047   1.0
delivery_time_deviation   1.259607  6.088516  9.247708  10.0
customs_clearance_time    0.777328  1.942439  3.749471   5.0

Supplier-level averages for the same product:
product_id supplier_id  order_fulfillment_status  cargo_condition_status  delivery_time_deviation  customs_clearance_time
     P0001    P0001_S1                  0.657594                0.219251                 5.017376                2.079872
     P0001    P0001_S2                  0.657594                0.219251                 5.017376                2.079872
     P0002    P0002_S1                  0.668762                0.254522                 4.683838                2.376317
     P0002    P0002_S2                  0.668762                0.254522                 4.683838                2.376317
     P0002    P0002_S3                  0.668762                0.254522                 4.683838                2.376317
     P0003    P0003_S1                  0.586810                0.213505                 4.419323                2.574446
     P0003    P0003_S2                  0.586810                0.213505                 4.419323                2.574446
     P0003    P0003_S3                  0.586810                0.213505                 4.419323                2.574446
     P0003    P0003_S4                  0.586810                0.213505                 4.419323                2.574446
     P0004    P0004_S1                  0.572918                0.317257                 5.392035                2.447231
     P0004    P0004_S2                  0.572918                0.317257                 5.392035                2.447231
     P0004    P0004_S3                  0.572918                0.317257                 5.392035                2.447231
     P0004    P0004_S4                  0.572918                0.317257                 5.392035                2.447231
     P0004    P0004_S5                  0.572918                0.317257                 5.392035                2.447231
     P0005    P0005_S1                  0.544506                0.390966                 5.463595                2.380356

Products where supplier averages differ:
order_fulfillment_status    0
cargo_condition_status      0
delivery_time_deviation     0
customs_clearance_time      0
dtype: int64

Missing values:
order_fulfillment_status    0
cargo_condition_status      0
delivery_time_deviation     0
customs_clearance_time      0
dtype: int64

In [29]:
print(df["order_fulfillment_status"].value_counts(dropna=False).head(10))
print(df["cargo_condition_status"].value_counts(dropna=False).head(10))
print(df[["order_fulfillment_status", "cargo_condition_status"]].dtypes)

order_fulfillment_status
1.000000    9
0.991061    9
1.000000    9
1.000000    8
0.999938    8
1.000000    8
0.999976    8
1.000000    7
1.000000    7
0.995404    7
Name: count, dtype: int64
cargo_condition_status
0.000012    23
0.000055    22
0.000001    20
0.000034    20
0.000013    19
0.000035    18
0.000075    18
0.000012    17
0.000010    17
0.000016    16
Name: count, dtype: int64
order_fulfillment_status    float64
cargo_condition_status      float64
dtype: object

In [30]:
def winsor_minmax(s, lo=0.01, hi=0.99):
    """Scale to 0-1 after clipping extreme tails, so outliers don't crush everyone else."""
    a, b = s.quantile(lo), s.quantile(hi)
    return ((s.clip(a, b) - a) / (b - a))

# Fulfilment: already a rate near 1 -> use directly (higher = better)
df["fulfil_score"] = df["order_fulfillment_status"].clip(0, 1)

# Cargo: ASSUMED to be a damage rate (lower = better) -> invert
df["cargo_score"] = 1 - winsor_minmax(df["cargo_condition_status"])

In [31]:
cols = ["order_fulfillment_status", "cargo_condition_status"]
print(df[cols].describe(percentiles=[.01, .05, .25, .5, .75, .95, .99]).T)
print(df[["fulfil_score", "cargo_score"]].describe().T)

# Make sure the synthetic date steps have actually been run before aggregating
needed = ["order_date", "dispatch_date", "expected_delivery_date", "actual_delivery_date",
          "lead_time_days_new", "delivery_time_deviation", "on_time"]
print("Missing columns:", [c for c in needed if c not in df.columns])

                             count      mean       std           min  \
order_fulfillment_status  113097.0  0.600992  0.345996  1.320000e-06
cargo_condition_status    113097.0  0.297268  0.321501  7.260000e-19

                                    1%        5%       25%       50%  \
order_fulfillment_status  1.622638e-03  0.022274  0.276788  0.681859
cargo_condition_status    4.100000e-07  0.000075  0.016840  0.155386

                               75%       95%       99%  max
order_fulfillment_status  0.938873  0.998909  0.999985  1.0
cargo_condition_status    0.540047  0.940789  0.993553  1.0
                 count      mean       std       min       25%       50%  \
fulfil_score  113097.0  0.600992  0.345996  0.000001  0.276788  0.681859
cargo_score   113097.0  0.700842  0.323504  0.000000  0.456449  0.843606

                   75%  max
fulfil_score  0.938873  1.0
cargo_score   0.983051  1.0
Missing columns: ['order_date', 'dispatch_date', 'expected_delivery_date', 'actual_delivery_date', 'lead_time_days_new', 'on_time']

In [32]:
ref = ["disruption_likelihood_score", "delay_probability", "supplier_reliability_score"]
cols = ["order_fulfillment_status", "cargo_condition_status"]
print(df[cols + ref].corr()[ref].loc[cols].round(3))

# Risk class view (adjust if risk_classification is categorical or numeric)
print(df.groupby("risk_classification")[cols].mean().round(3))

                          disruption_likelihood_score  delay_probability  \
order_fulfillment_status                       -0.009              0.006
cargo_condition_status                          0.011              0.003

                          supplier_reliability_score
order_fulfillment_status                       0.003
cargo_condition_status                        -0.008
                     order_fulfillment_status  cargo_condition_status
risk_classification
High Risk                               0.599                   0.299
Low Risk                                0.601                   0.281
Moderate Risk                           0.611                   0.301

In [33]:
# ASSUMPTION (document in report): both columns are 0-1 scores, higher = better.
CARGO_HIGHER_IS_BETTER = True
FULFIL_HIGHER_IS_BETTER = True

df["fulfil_score"] = df["order_fulfillment_status"].clip(0, 1)
df["cargo_score"] = df["cargo_condition_status"].clip(0, 1)
if not FULFIL_HIGHER_IS_BETTER:
    df["fulfil_score"] = 1 - df["fulfil_score"]
if not CARGO_HIGHER_IS_BETTER:
    df["cargo_score"] = 1 - df["cargo_score"]

In [38]:
SUP, CTRY = "supplier_id", "supplier_country"

SEED = 42
rng = np.random.default_rng(SEED)
START = pd.Timestamp("2023-01-01")
n = len(df)

# Supplier-level latent quality (separates suppliers of the same product)
sup_quality = pd.Series(rng.beta(5, 2, df[SUP].nunique()), index=df[SUP].unique())
q = df[SUP].map(sup_quality).to_numpy()
ctry_transit = pd.Series(rng.integers(3, 26, df[CTRY].nunique()), index=df[CTRY].unique())

# Planned timeline
order_date = START + pd.to_timedelta(rng.integers(0, 730, n), unit="D")
planned_proc = rng.integers(1, 6, n)
planned_transit = np.clip(df[CTRY].map(ctry_transit).to_numpy() + rng.integers(-2, 3, n), 2, None)
expected_dispatch = order_date + pd.to_timedelta(planned_proc, unit="D")
expected_delivery = expected_dispatch + pd.to_timedelta(planned_transit, unit="D")

# Actual timeline (lower-quality suppliers -> more delay)
dispatch_delay = rng.poisson((1 - q) * 3)
transit_delay = rng.poisson((1 - q) * 3)
early = rng.binomial(1, 0.25 * q) * rng.integers(1, 3, n)
actual_dispatch = expected_dispatch + pd.to_timedelta(dispatch_delay, unit="D")
actual_delivery = actual_dispatch + pd.to_timedelta(planned_transit + transit_delay - early, unit="D")

df["order_date"] = order_date
df["dispatch_date"] = actual_dispatch
df["expected_delivery_date"] = expected_delivery
df["actual_delivery_date"] = actual_delivery

# Keep the dataset's original deviation for reference only
if "delivery_time_deviation_orig" not in df.columns:
    df = df.rename(columns={"delivery_time_deviation": "delivery_time_deviation_orig"})

df["lead_time_days_new"] = (df["actual_delivery_date"] - df["order_date"]).dt.days
df["expected_lead_time_days"] = (df["expected_delivery_date"] - df["order_date"]).dt.days
df["delivery_time_deviation"] = (df["actual_delivery_date"] - df["expected_delivery_date"]).dt.days  # + late, - early
df["on_time"] = (df["delivery_time_deviation"] <= 0).astype(int)

assert (df["order_date"] <= df["dispatch_date"]).all()
assert (df["dispatch_date"] <= df["actual_delivery_date"]).all()
assert df["lead_time_days_new"].gt(0).all()

needed = ["order_date", "dispatch_date", "expected_delivery_date", "actual_delivery_date",
          "lead_time_days_new", "delivery_time_deviation", "on_time"]
print("Missing columns:", [c for c in needed if c not in df.columns])
print(df[["lead_time_days_new", "expected_lead_time_days", "delivery_time_deviation"]].describe().T)
print("On-time rate:", round(df["on_time"].mean(), 3))

Missing columns: []
                            count       mean       std  min   25%   50%   75%  \
lead_time_days_new       113097.0  18.429419  6.942255  1.0  13.0  18.0  24.0
expected_lead_time_days  113097.0  17.002166  6.712514  3.0  11.0  17.0  23.0
delivery_time_deviation  113097.0   1.427253  1.764013 -2.0   0.0   1.0   2.0

                          max
lead_time_days_new       41.0
expected_lead_time_days  32.0
delivery_time_deviation  13.0
On-time rate: 0.335

In [39]:
rng = np.random.default_rng(SEED)          # reset so the full sequence reproduces
sup_quality = pd.Series(rng.beta(5, 2, df[SUP].nunique()), index=df[SUP].unique())
q = df[SUP].map(sup_quality).to_numpy()
ctry_transit = pd.Series(rng.integers(3, 26, df[CTRY].nunique()), index=df[CTRY].unique())

order_date = START + pd.to_timedelta(rng.integers(0, 730, n), unit="D")
planned_proc = rng.integers(1, 6, n)
planned_transit = np.clip(df[CTRY].map(ctry_transit).to_numpy() + rng.integers(-2, 3, n), 3, None)
expected_dispatch = order_date + pd.to_timedelta(planned_proc, unit="D")
expected_delivery = expected_dispatch + pd.to_timedelta(planned_transit, unit="D")

# Recalibrated: smaller delay rates, and a chance of on-schedule/early that grows with quality
dispatch_delay = rng.poisson((1 - q) * 1.5)
transit_delay = rng.poisson((1 - q) * 1.5)
early = rng.binomial(1, 0.4 * q) * rng.integers(1, 3, n)
actual_dispatch = expected_dispatch + pd.to_timedelta(dispatch_delay, unit="D")
actual_delivery = actual_dispatch + pd.to_timedelta(planned_transit + transit_delay - early, unit="D")

df["order_date"] = order_date
df["dispatch_date"] = actual_dispatch
df["expected_delivery_date"] = expected_delivery
df["actual_delivery_date"] = actual_delivery

df["lead_time_days_new"] = (df["actual_delivery_date"] - df["order_date"]).dt.days
df["expected_lead_time_days"] = (df["expected_delivery_date"] - df["order_date"]).dt.days
df["delivery_time_deviation"] = (df["actual_delivery_date"] - df["expected_delivery_date"]).dt.days
df["on_time"] = (df["delivery_time_deviation"] <= 0).astype(int)

assert (df["order_date"] <= df["dispatch_date"]).all()
assert (df["dispatch_date"] <= df["actual_delivery_date"]).all()
print(df[["lead_time_days_new", "expected_lead_time_days", "delivery_time_deviation"]].describe().T)
print("On-time rate:", round(df["on_time"].mean(), 3))
print("Shipments with lead time < 4 days:", (df["lead_time_days_new"] < 4).sum())

                            count       mean       std  min   25%   50%   75%  \
lead_time_days_new       113097.0  17.442549  6.800039  2.0  12.0  17.0  23.0
expected_lead_time_days  113097.0  17.025270  6.672795  4.0  11.0  17.0  23.0
delivery_time_deviation  113097.0   0.417279  1.296411 -2.0   0.0   0.0   1.0

                          max
lead_time_days_new       37.0
expected_lead_time_days  32.0
delivery_time_deviation   9.0
On-time rate: 0.579
Shipments with lead time < 4 days: 327

In [40]:
g = df.groupby(SUP)
sup = pd.DataFrame({
    "avg_lead_time_days": g["lead_time_days_new"].mean(),
    "lead_time_std": g["lead_time_days_new"].std(),
    "avg_delivery_deviation": g["delivery_time_deviation"].mean(),
    "avg_late_days": g["delivery_time_deviation"].apply(lambda x: x.clip(lower=0).mean()),
    "on_time_rate": g["on_time"].mean(),
    "fulfilment_perf": g["fulfil_score"].mean(),
    "cargo_perf": g["cargo_score"].mean(),
    "n_shipments": g.size(),
})

late = sup["avg_late_days"]
sup["delay_score"] = 1 - (late - late.min()) / (late.max() - late.min())

WEIGHTS = {"on_time_rate": 0.30, "delay_score": 0.20, "fulfilment_perf": 0.25, "cargo_perf": 0.25}
sup["supplier_reliability_score_new"] = 100 * sum(sup[c] * w for c, w in WEIGHTS.items())

print(sup[["avg_lead_time_days", "lead_time_std", "on_time_rate",
           "fulfilment_perf", "cargo_perf", "supplier_reliability_score_new"]].describe().T)

                                 count       mean       std        min  \
avg_lead_time_days              3524.0  17.438944  6.415020   5.540541
lead_time_std                   3524.0   2.276325  0.293724   1.238731
on_time_rate                    3524.0   0.578801  0.211765   0.029412
fulfilment_perf                 3524.0   0.601561  0.062063   0.378305
cargo_perf                      3524.0   0.297835  0.055833   0.110169
supplier_reliability_score_new  3524.0  54.908294  9.861390  21.907581

                                      25%        50%        75%        max
avg_lead_time_days              11.881765  17.147245  23.030303  29.677419
lead_time_std                    2.080399   2.266873   2.469057   3.532202
on_time_rate                     0.421053   0.586207   0.750000   1.000000
fulfilment_perf                  0.559163   0.601062   0.642168   0.786158
cargo_perf                       0.261049   0.294920   0.333019   0.477958
supplier_reliability_score_new  48.208707  55.689763  62.393353  75.918260

In [41]:
# Cell 3: sensitivity check, simulation check, merge back into df
from scipy.stats import spearmanr

# 1) Cargo direction sensitivity (mean of 1-x equals 1 minus mean of x)
flip = sup.copy()
flip["cargo_perf"] = 1 - flip["cargo_perf"]
sup_flip_score = 100 * sum(flip[c] * w for c, w in WEIGHTS.items())
print("Rank corr, cargo higher=better vs lower=better:",
      round(spearmanr(sup["supplier_reliability_score_new"], sup_flip_score)[0], 3))
print("Mean score if cargo flipped:", round(sup_flip_score.mean(), 1))

# 2) Simulation check: does the score recover the latent quality I generated?
# Only valid if sup_quality is still in memory from the date-generation cell
print("Rank corr with simulated quality:",
      round(spearmanr(sup["supplier_reliability_score_new"],
                      sup_quality.reindex(sup.index))[0], 3))

# 3) Merge supplier-level values back into df (drops old copies so re-running is safe)
add = sup[["avg_lead_time_days", "lead_time_std", "on_time_rate",
           "supplier_reliability_score_new", "n_shipments"]].add_prefix("sup_")
df = df.drop(columns=[c for c in add.columns if c in df.columns])
df = df.merge(add, left_on=SUP, right_index=True, how="left")
print(df.shape, df[add.columns].isna().sum().sum(), "missing after merge")

Rank corr, cargo higher=better vs lower=better: 0.959
Mean score if cargo flipped: 65.0
Rank corr with simulated quality: 0.911
(113097, 33) 0 missing after merge

In [42]:
# Cell 4: is there any signal in the original labels?
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import HistGradientBoostingClassifier, HistGradientBoostingRegressor

feat = ["warehouse_inventory_level", "handling_equipment_availability",
        "weather_condition_severity", "shipping_costs", "historical_demand",
        "route_risk_level", "customs_clearance_time", "fulfil_score", "cargo_score",
        "sup_avg_lead_time_days", "sup_lead_time_std", "sup_on_time_rate",
        "sup_supplier_reliability_score_new"]
X = df[feat].apply(pd.to_numeric, errors="coerce")

y = df["risk_classification"]
print("Majority-class baseline:", round(y.value_counts(normalize=True).max(), 3))
print("Model accuracy:", round(cross_val_score(HistGradientBoostingClassifier(),
      X, y, cv=3, scoring="accuracy").mean(), 3))

y2 = df["disruption_likelihood_score"]
print("R2 on disruption_likelihood_score:", round(cross_val_score(
      HistGradientBoostingRegressor(), X, y2, cv=3, scoring="r2").mean(), 3))

Majority-class baseline: 0.746
Model accuracy: 0.743
R2 on disruption_likelihood_score: -0.018

In [43]:
# Cell 5: new target, leakage-free supplier history, time-based split
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score, average_precision_score

df = df.sort_values("order_date").reset_index(drop=True)
df["late_2d"] = (df["delivery_time_deviation"] >= 2).astype(int)
print("Positive rate:", round(df["late_2d"].mean(), 3))

# Supplier history from EARLIER orders only (shift(1) excludes the current shipment)
g = df.groupby(SUP)
df["hist_n"] = g.cumcount()
df["hist_on_time"] = g["on_time"].transform(lambda s: s.shift(1).expanding().mean())
df["hist_late_rate"] = g["late_2d"].transform(lambda s: s.shift(1).expanding().mean())
df["hist_mean_dev"] = g["delivery_time_deviation"].transform(lambda s: s.shift(1).expanding().mean())

feat = ["hist_n", "hist_on_time", "hist_late_rate", "hist_mean_dev",
        "expected_lead_time_days", "route_risk_level", "weather_condition_severity",
        "customs_clearance_time", "warehouse_inventory_level", "shipping_costs"]
X = df[feat].apply(pd.to_numeric, errors="coerce")
y = df["late_2d"]

cutoff = df["order_date"].quantile(0.7)
tr, te = df["order_date"] < cutoff, df["order_date"] >= cutoff

m = HistGradientBoostingClassifier(random_state=42).fit(X[tr], y[tr])
p = m.predict_proba(X[te])[:, 1]
print("Test positive rate (baseline PR-AUC):", round(y[te].mean(), 3))
print("ROC-AUC:", round(roc_auc_score(y[te], p), 3))
print("PR-AUC:", round(average_precision_score(y[te], p), 3))

Positive rate: 0.173
Test positive rate (baseline PR-AUC): 0.173
ROC-AUC: 0.753
PR-AUC: 0.38

In [44]:
# Cell 6: what is the model actually using?
from sklearn.inspection import permutation_importance

imp = permutation_importance(m, X[te], y[te], scoring="roc_auc",
                             n_repeats=5, random_state=42)
print(pd.Series(imp.importances_mean, index=feat).sort_values(ascending=False).round(4))

# Ablation: history-only vs real-columns-only
hist_cols = ["hist_n", "hist_on_time", "hist_late_rate", "hist_mean_dev"]
real_cols = ["route_risk_level", "weather_condition_severity", "customs_clearance_time",
             "warehouse_inventory_level", "shipping_costs", "expected_lead_time_days"]
for name, cols in [("history only", hist_cols), ("real columns only", real_cols)]:
    mm = HistGradientBoostingClassifier(random_state=42).fit(X.loc[tr, cols], y[tr])
    print(name, "ROC-AUC:", round(roc_auc_score(y[te], mm.predict_proba(X.loc[te, cols])[:, 1]), 3))

hist_mean_dev                 0.1593
hist_on_time                  0.0118
hist_late_rate                0.0062
shipping_costs                0.0002
hist_n                       -0.0000
weather_condition_severity   -0.0000
route_risk_level             -0.0001
expected_lead_time_days      -0.0001
warehouse_inventory_level    -0.0001
customs_clearance_time       -0.0003
dtype: float64
history only ROC-AUC: 0.749
real columns only ROC-AUC: 0.488